services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_APP_NAME=Shortify
        - VITE_BACKEND_URL=http://server:8000
        - VITE_DOMAIN=localhost:5173/r
    container_name: short-url-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: short-url-server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
